{
 "title": "numerical feature",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } },
   {
    "name": "feature",
    "query": {
     "query": "label_values(evidently:data_quality:quality_stat{dataset_name=\"${dataset_name:raw}\",feature_type=\"num\"},feature)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Numerical Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Numberical Feature Metrics\n\n Chose Dataset and Feature\n         "
   },
   "targets": [
    {}
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Reference Dataset Mean",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"mean\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset Mean",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"mean\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset std",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"std\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset std",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"std\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset min",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"min\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"min\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset max",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"max\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"num\",metric=\"max\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset Number of Missing",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",metric=\"missing_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset Number of Missing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",metric=\"missing_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}