{
 "title": "categorical feature",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataset_name", "query": { "query": "label_values(dataset_name)" } },
   {
    "name": "feature",
    "query": {
     "query": "label_values(evidently:data_quality:quality_stat{dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\"},feature)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Categirical Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Categorical Feature Metrics\n\n Chose Dataset and Feature\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reference Dataset Unique Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\",metric=\"unique_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset Unique Values",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\",metric=\"unique_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset Most Common Value",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\",metric=\"most_common_value\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset Most Common Feature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\",metric=\"most_common_value\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Reference Dataset Number of Missing",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"reference\",dataset_name=\"${dataset_name:raw}\",metric=\"missing_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset Number of Missing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",metric=\"missing_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  },
  {
   "title": "Production Dataset New Feature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "evidently:data_quality:quality_stat{dataset=\"current\",dataset_name=\"${dataset_name:raw}\",feature_type=\"cat\",metric=\"new_in_current_values_count\",feature=\"${feature:raw}\"}",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}